language: cpp

jobs:
  allow_failures:
    - env: ALLOW_FAILURES=true

  include:
    - name: Ubuntu 18.04
      os: linux
      dist: bionic

    - name: Ubuntu 16.04
      os: linux
      dist: xenial

    - name: Windows 10
      os: windows
      env:
        - MSBUILD_PATH="c:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin"
        - PATH_FIX="C:\Windows\System32"

    - name: MacOS
      os: osx


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get update;
      sudo apt-get -y install git wget unzip;
      sudo apt-get -y install build-essential software-properties-common cmake rsync libboost-all-dev;
    elif [[ "$TRAVIS_OS_NAME" == "osx" ]] && [[ "$TOOL" == "cmake" ]]; then
      echo "No before_install actions for OSX";
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      ./setup.sh;
      ./build.sh;
      cd Unity && ./build.sh 2> Unity_error.txt || (tail -n 100 Unity_error.txt && exit 1);
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      export PATH=$MSBUILD_PATH:$PATH_FIX:$PATH;
      cmd.exe //C 'C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Auxiliary\Build\vcvarsall.bat' amd64 '&&'
      build.cmd '&&'
      cd Unity '&&' build.cmd;
    elif  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      ./setup.sh;
      ./build.sh;
      cd Unity && ./build.sh 2> Unity_error.txt || (tail -n 100 Unity_error.txt && exit 1);
    fi
